function LUXmeterlightONavg = importf_lux(filename, startRow, endRow)
%IMPORTFILE Import numeric data from a text file as a matrix.
%   LUXMETERLIGHTONAVG = IMPORTFILE(FILENAME) Reads data from text file
%   FILENAME for the default selection.
%
%   LUXMETERLIGHTONAVG = IMPORTFILE(FILENAME, STARTROW, ENDROW) Reads data
%   from rows STARTROW through ENDROW of text file FILENAME.
%
% Example:
%   LUXmeterlightONavg = importfile('LUXmeter_lightON_avg.txt', 2, 62);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2018/10/18 23:33:11

%% Initialize variables.
delimiter = '\t';
if nargin<=2
    startRow = 2;
    endRow = inf;
end

%% Format for each line of text:
%   column1: double (%f)
%	column2: datetimes (%{MM/dd/yy HH:mm:ss}D)
%   column3: double (%f)
%	column4: text (%s)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%f%{MM/dd/yy HH:mm:ss}D%f%s%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'TextType', 'string', 'HeaderLines', startRow(1)-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
for block=2:length(startRow)
    frewind(fileID);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'TextType', 'string', 'HeaderLines', startRow(block)-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Create output variable
LUXmeterlightONavg = table(dataArray{2:end-2}, 'VariableNames', {'DateTime','Illumination'});

% For code requiring serial dates (datenum) instead of datetime, uncomment
% the following line(s) below to return the imported dates as datenum(s).

% LUXmeterlightONavg.VarName2=datenum(LUXmeterlightONavg.VarName2);

